---
- name: "Assertions: ar_tls_ca"
  assert:
    that: "{{ ar_tls_ca_git_assertions }}"

- include_role:
    name: ar_git_repo
    tasks_from: update
  vars:
    ar_git_repo_url: "{{ ar_tls_ca_git_repo }}"
    ar_git_repo_ssh_key: "{{ ar_tls_ca_git_ssh_key }}"
    ar_git_repo_ssh_key_pass: "{{ ar_tls_ca_git_ssh_key_pass | default('') }}"
    ar_git_repo_commit_comment: "{{ ar_tls_ca_git_comment | default('') }}"
