---
- name: "Assert ..."
  assert:
    that:
      - "ar_tls_ca_path is not none"
      - "ar_tls_ca_name is not none"
      - "ar_tls_ca_git_repo is none or (ar_tls_ca_git_repo is not none and ar_tls_ca_git_repo_path is defined)"
    msg: "Must include required parameters: ar_tls_ca_path, ar_tls_ca_name and if including git (ar_tls_ca_git_repo), must include ar_tls_ca_git_repo_path"

- name: Include git checkout
  include_tasks: git-checkout.yml
  when: ar_tls_ca_git_repo is not none

- name: Ensure CA keys are present
  include_tasks: ensure_keys.yml
  vars:
    keys_present: true

- name: Ensure directory structure
  file:
    path: "{{ ar_tls_ca_item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ ar_tls_ca_path }}"
    - "{{ ar_tls_ca_path }}/newcerts"
    - "{{ ar_tls_ca_out }}"
    - "{{ ar_tls_ca_in }}"
    - "{{ ar_tls_ca_sancfg }}"
  loop_control:
    loop_var: ar_tls_ca_item

- name: "Stat the CA database file"
  stat:
    path: '{{ ar_tls_ca_database }}'
  register: ar_tls_ca_database_

- name: "Stat the serial file"
  stat:
    path: '{{ ar_tls_ca_serial }}'
  register: ar_tls_ca_serial_

- name: Ensure CA database file present
  file:
    path: "{{ ar_tls_ca_database }}"
    state: touch
  when: not ar_tls_ca_database_.stat.exists | bool

- name: Ensure serial file present
  copy:
    dest: "{{ ar_tls_ca_serial }}"
    content: '01'
  when: not ar_tls_ca_serial_.stat.exists | bool

- name: Generate the CA config file
  template:
    src: ca.cfg.j2
    dest: "{{ ar_tls_ca_path }}/ca.cfg"

- name: Generate the CA key
  shell: "openssl genrsa -out {{ ar_tls_ca_path }}/{{ ar_tls_ca_name }}.key 2048"
  args:
    creates: "{{ ar_tls_ca_path }}/{{ ar_tls_ca_name }}.key"

- name: Vault the keys
  import_tasks: vault.yml

- name: Self sign the CA key
  shell: "openssl req -new -x509 -key {{ ar_tls_ca_path }}/{{ ar_tls_ca_name }}.key -out \
          {{ ar_tls_ca_path }}/{{ ar_tls_ca_name }}.crt -subj \"/CN=ca.{{ ar_tls_ca_name }}\" -days {{ ar_tls_ca_ca_default_days }}"
  args:
    creates: "{{ ar_tls_ca_path }}/{{ ar_tls_ca_name }}.crt"

- name: Copy CA crt to out dir
  copy:
    src: "{{ ar_tls_ca_path }}/{{ ar_tls_ca_name }}.crt"
    dest: "{{ ar_tls_ca_out }}/{{ ar_tls_ca_name }}.crt"
    remote_src: yes

# This will remove the CA keys from the file system
- name: Include signing of certs
  import_tasks: sign.yml

- name: Include git checkin
  include_tasks: git-checkin.yml
  vars:
    comment: "automated build changes as of {{ ansible_date_time.date }} {{ ansible_date_time.time }}"
  when: ar_tls_ca_git_repo is not none
