---
- set_fact:
    ar_tls_ca_base_path: "{{ ar_tls_ca_git_repo_path }}"

- set_fact:
    ar_tls_ca_vault_path: "{{ ar_tls_ca_git_repo_path }}/{{ ar_tls_ca_name }}/{{ ar_tls_ca_vault_file }}"

- name: check if vault exists
  stat:
    path: "{{ ar_tls_ca_vault_path }}"
  register: vault_file

