---
- name: Converge
  hosts: all

  tasks:
    - name: "Setup CA"
      include_role:
        name: tls_ca
      vars:
        tls_ca_path: "/tmp/ca"
        tls_ca_name: "test-ca"
        tls_ca_certlist: [
          {"certfile": "my-cert-1.crt", "csrfile": "my-cert-1.csr", "altnames": ["my-cert-1.domain"], "ipaddrs": ["1.2.3.4"]},
          {"certfile": "my-cert-2.crt", "csrfile": "my-cert-2.csr", "altnames": ["my-cert-2.domain"], "ipaddrs": ["1.2.3.4"]}
        ]
